version: "3.7"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ./redis:/data
  backend:
    image: tkp75/backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.10'
    depends_on:
      - redis
      - db
    volumes:
      - backend_logs:/home/node/logs
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=pgpass
  frontend:
    image: tkp75/frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: '0.10'
    volumes:
      - frontend_logs:/home/node/logs
  nginx:
    image: tkp75/nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.10'
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:80:80
volumes:
  backend_logs:
  frontend_logs:
