version: "3.5"
services: 
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpass
  redis:
    image: redis
    container_name: redis
  backend: 
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    depends_on:
      - redis
      - db
    volumes:
      - backend_logs:/home/node/logs
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=pgpass
  frontend: 
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - frontend_logs:/home/node/logs
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:80:80
volumes:
  backend_logs:
  frontend_logs:
