version: "3.5"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ./redis:/data
  backend:
    image: backend:3.6
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - redis
      - db
    volumes:
      - backend_logs:/home/node/logs
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=pgpass
  frontend:
    image: frontend:3.6
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - frontend_logs:/home/node/logs
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:80:80
volumes:
  backend_logs:
  frontend_logs:
