version: "3"
services: 
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: pgpass
      container_name: db
    redis:
      image: redis
      expose:
        - 6379
    backend: 
      build:
        context: .
        dockerfile: Dockerfile.backend
      depends_on:
        - redis
        - db
      ports: 
        - 8000:8000
      volumes:
        - backend_logs:/home/node/logs
      environment:
        - REDIS=redis
        - DB_HOST=db
        - DB_USERNAME=postgres
        - DB_PASSWORD=pgpass
    frontend: 
      build:
        context: .
        dockerfile: Dockerfile.frontend
      depends_on:
        - backend
      ports: 
        - 5000:5000
      volumes:
        - frontend_logs:/home/node/logs
volumes:
  backend_logs:
  frontend_logs:
